### ISSUE TITLE
Exposing golang direct to Flutter

### ISSUE THREAD

**Issue by gedw99** [xlab/android-go#20]
Its all explained here:
https://github.com/flutter/flutter/issues/7053

Basically at the moment if you want to use golang with flutter so need to write Java and Objective C wrappers. I have been doing it this way using gomobile bind and then writing wrappers. Quite painful and high latency.

So many cpp programmers have been asking the Flutter Team for direct calls between cpp and flutter, and the Flutter team are have listened and are exposing it.

SO i think think that maybe android-go and ios-go would fit in their well. 

Also i noticed that already have FlatBuffers exposed between Dart and cpp and golang.
https://github.com/dnfield/flatbuffers/blob/master/samples/sample_binary.go.

**Comment by xlab** [comment]
I have very little knowledge of its context.. :(
Also, it's about using Go from Flutter, but these projects (android-go, ios-go) are achieving sometinh reverse — using SDKs from outside in Go.

**Comment by gedw99** [comment]
ah you might be right. Sorry did not realise.
I thought your repo related to being able to compile shared libs for mobiles. 
gomobile build compile to an APK which is not what i want.
gomobile bind compiles to an aar which is not what i want.

**Comment by xlab** [comment]
> I thought your repo related to being able to compile shared libs for mobiles.

this is possible with default Go toolchain, without libs. This package is for interaction with Android SDK without using JVM. Also, for interacting with JNI and JVM if needed.
