### ISSUE TITLE
internal/callfn error when running main.go file

### ISSUE THREAD

**Issue by r3mb00** [xlab/android-go#25]
Hi, @xlab

I  try go run main.go but got this error:

![screenshot at 2018-06-21 09-38-02](https://user-images.githubusercontent.com/9653037/41714349-0d5c20a8-751e-11e8-849a-e1232272484c.png)

Please help.

**Comment by xlab** [comment]
You cannot run android apps on desktop, should deploy them on device using commands from `Makefile`

**Comment by r3mb00** [comment]
Hi, @xlab.

Unfortunatelly I don't have android device but was hopping to generate apk file to run somewhere in cloud, VM etc.

**Comment by xlab** [comment]
@r3mb00 the makefile generates an APK artefact. You then decide what to do with it. You don't need a device to comopile the app, however `go run` is not enough.

**Comment by r3mb00** [comment]
@xlab I did ANDROID_HOME=path/to/sdk ../build-android.sh" to build an APK ready for deployment from Minimal Go app page but couldn't find apk.

I search all directories and subdirectories but found nothing did I do something wrong ?

**Comment by Noofbiz** [comment]
You have to get the android sdk and ndk. The easiest way to do that is installing Android studio and getting it through the package manager in Android studio. It also comes with Android emulators you can test the built apk out on.

**Comment by r3mb00** [comment]
@Noofbiz thank you for the help.

I installed Android Studio and NDK with the SDK Manager sd you adviced:
![screenshot at 2018-06-28 10-36-44](https://user-images.githubusercontent.com/9653037/42046530-b979adb0-7ac3-11e8-9b7b-f85990f586f7.png)
![screenshot at 2018-06-28 10-36-55](https://user-images.githubusercontent.com/9653037/42046531-b9a064e6-7ac3-11e8-810f-b21b1ac07bf2.png)
![screenshot at 2018-06-28 11-07-44](https://user-images.githubusercontent.com/9653037/42046532-b9c67208-7ac3-11e8-92bc-922272c620bb.png)
![screenshot at 2018-06-28 13-08-42](https://user-images.githubusercontent.com/9653037/42046533-b9edea7c-7ac3-11e8-8e5d-bf3dad3b7f81.png)
![screenshot at 2018-06-28 13-08-55](https://user-images.githubusercontent.com/9653037/42046534-ba180c9e-7ac3-11e8-9ae4-56c89fa59378.png)
![screenshot at 2018-06-28 13-09-11](https://user-images.githubusercontent.com/9653037/42046535-ba47b264-7ac3-11e8-9413-ae874d7bb719.png)
![screenshot at 2018-06-28 13-09-27](https://user-images.githubusercontent.com/9653037/42046536-ba6e8e52-7ac3-11e8-9dd9-eb5fd656ef75.png)
![screenshot at 2018-06-28 13-09-36](https://user-images.githubusercontent.com/9653037/42046537-ba954b8c-7ac3-11e8-9b9d-d3ef09936b95.png)
![screenshot at 2018-06-28 13-09-48](https://user-images.githubusercontent.com/9653037/42046539-babcd04e-7ac3-11e8-968a-6767630632e3.png)
![screenshot at 2018-06-28 13-09-53](https://user-images.githubusercontent.com/9653037/42046540-bae350fc-7ac3-11e8-8d70-1010ec968658.png)
![screenshot at 2018-06-28 14-05-08](https://user-images.githubusercontent.com/9653037/42046541-bb12db60-7ac3-11e8-9c6a-da8d6500198a.png)
![screenshot at 2018-06-28 14-05-16](https://user-images.githubusercontent.com/9653037/42046543-bb4134ba-7ac3-11e8-91f6-dfe281190189.png)

@Noofbiz @xlab what next should I do?
Can you help please ?
