### ISSUE TITLE
App: Add asset streaming 

### ISSUE THREAD

**Issue by MaVo159** [xlab/android-go#8]
App should offer something like `GetAssetReader(name string) io.ReadCloser` to allow streaming large assets. The NDK functions work like that way anyway. See #7 for why this may not be trivial.

**Comment by xlab** [comment]
Seems to be trivial, we should acquire AssetManager and wrap it with AssetReader that will manage locking and chunked reads (see the final version of #7).

**Comment by MaVo159** [comment]
Ah, now I get why you added that. The AssetManager is actually thread safe according to the docs. The problem is AAsset. The mutex should be in the io.ReadCloser that contains the reference to AAsset (assuming that this is indeed trivial, I'm not 100% sure about that, because I can't wrap my head around the panic I got).

**Comment by xlab** [comment]
@MaVo159 
As long as
> AssetManager is actually thread safe

This is ok:
> The mutex should be in the io.ReadCloser

I'll leave the implementation up to you, I have nothing to test..
